export const ASSETS = {
  logo:         "/images/logo.png",
  langArrow:    "/images/lang-arrow.svg",
  heroBg:       "/images/hero-bg.jpg",
  heroArrow:    "/images/hero-arrow.svg",
  adv1:         "/images/adv-1.svg",
  adv2:         "/images/adv-2.svg",
  adv3:         "/images/adv-3.svg",
  adv4:         "/images/adv-4.svg",
  adv5:         "/images/adv-5.svg",
  adv6:         "/images/adv-6.svg",
  includedPhoto:"/images/included-photo.jpg",
  checkIcon:    "/images/check-icon.svg",
  badgeStar:    "/images/badge-star.svg",
  addlIcon:     "/images/addl-icon.svg",
  equipKirby:   "/images/equip-kirby.svg",
  equipSabrina: "/images/equip-sabrina.svg",
  equipKarcher: "/images/equip-karcher.svg",
  equipRaypath: "/images/equip-raypath.svg",
  guar1:        "/images/guar-1.svg",
  guar2:        "/images/guar-2.svg",
  guar3:        "/images/guar-3.svg",
  ctaCall:      "/images/cta-call.svg",
  ctaEnvelope:  "/images/cta-envelope.svg",
  ctaArrow:     "/images/cta-arrow.svg",
};